import { Geist, Geist_Mono ,Nosifer ,Rye,Rubik_Distressed} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nosifer = Nosifer({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-nosifer',
});
const rye = Rye({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-rye',
});
const rubikDistressed = Rubik_Distressed({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-embed_code',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nosifer.variable}  ${rye.variable} ${rubikDistressed.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
